package entities;
// Generated 07-sep-2015 11:55:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Bacteriologia generated by hbm2java
 */
public class Bacteriologia  implements java.io.Serializable {


     private Integer idbacteriologia;
     private Pacientes pacientes;
     private Doctores doctores;
     private Date fechaentrada;
     private Date fechasalida;
     private String observaciones;
     private String rctobacteriano;
     private String seaisla;
     private String sensiablea;
     private String resistentea;
     private String muestra;

    public Bacteriologia() {
    }

    public Bacteriologia(Pacientes pacientes, Doctores doctores, Date fechaentrada, Date fechasalida, String observaciones, String rctobacteriano, String seaisla, String sensiablea, String resistentea, String muestra) {
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.fechaentrada = fechaentrada;
       this.fechasalida = fechasalida;
       this.observaciones = observaciones;
       this.rctobacteriano = rctobacteriano;
       this.seaisla = seaisla;
       this.sensiablea = sensiablea;
       this.resistentea = resistentea;
       this.muestra = muestra;
    }
   
    public Integer getIdbacteriologia() {
        return this.idbacteriologia;
    }
    
    public void setIdbacteriologia(Integer idbacteriologia) {
        this.idbacteriologia = idbacteriologia;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public Date getFechaentrada() {
        return this.fechaentrada;
    }
    
    public void setFechaentrada(Date fechaentrada) {
        this.fechaentrada = fechaentrada;
    }
    public Date getFechasalida() {
        return this.fechasalida;
    }
    
    public void setFechasalida(Date fechasalida) {
        this.fechasalida = fechasalida;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getRctobacteriano() {
        return this.rctobacteriano;
    }
    
    public void setRctobacteriano(String rctobacteriano) {
        this.rctobacteriano = rctobacteriano;
    }
    public String getSeaisla() {
        return this.seaisla;
    }
    
    public void setSeaisla(String seaisla) {
        this.seaisla = seaisla;
    }
    public String getSensiablea() {
        return this.sensiablea;
    }
    
    public void setSensiablea(String sensiablea) {
        this.sensiablea = sensiablea;
    }
    public String getResistentea() {
        return this.resistentea;
    }
    
    public void setResistentea(String resistentea) {
        this.resistentea = resistentea;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }




}


