package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Heces generated by hbm2java
 */
public class Heces  implements java.io.Serializable {


     private int idheces;
     private Pacientes pacientes;
     private Doctores doctores;
     private String observaciones;
     private Date fecha;
     private String color;
     private String mucus;
     private String leucocitos;
     private String eritrocitos;
     private String ramacro;
     private String ramicro;
     private String bacterias;
     private String levaduras;
     private String sangreoculta;
     private String trofozoitos;
     private String huevos;
     private String quistes;
     private String larvas;
     private String otros;

    public Heces() {
    }

	
    public Heces(int idheces) {
        this.idheces = idheces;
    }
    public Heces(int idheces, Pacientes pacientes, Doctores doctores, String observaciones, Date fecha, String color, String mucus, String leucocitos, String eritrocitos, String ramacro, String ramicro, String bacterias, String levaduras, String sangreoculta, String trofozoitos, String huevos, String quistes, String larvas, String otros) {
       this.idheces = idheces;
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.observaciones = observaciones;
       this.fecha = fecha;
       this.color = color;
       this.mucus = mucus;
       this.leucocitos = leucocitos;
       this.eritrocitos = eritrocitos;
       this.ramacro = ramacro;
       this.ramicro = ramicro;
       this.bacterias = bacterias;
       this.levaduras = levaduras;
       this.sangreoculta = sangreoculta;
       this.trofozoitos = trofozoitos;
       this.huevos = huevos;
       this.quistes = quistes;
       this.larvas = larvas;
       this.otros = otros;
    }
   
    public int getIdheces() {
        return this.idheces;
    }
    
    public void setIdheces(int idheces) {
        this.idheces = idheces;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMucus() {
        return this.mucus;
    }
    
    public void setMucus(String mucus) {
        this.mucus = mucus;
    }
    public String getLeucocitos() {
        return this.leucocitos;
    }
    
    public void setLeucocitos(String leucocitos) {
        this.leucocitos = leucocitos;
    }
    public String getEritrocitos() {
        return this.eritrocitos;
    }
    
    public void setEritrocitos(String eritrocitos) {
        this.eritrocitos = eritrocitos;
    }
    public String getRamacro() {
        return this.ramacro;
    }
    
    public void setRamacro(String ramacro) {
        this.ramacro = ramacro;
    }
    public String getRamicro() {
        return this.ramicro;
    }
    
    public void setRamicro(String ramicro) {
        this.ramicro = ramicro;
    }
    public String getBacterias() {
        return this.bacterias;
    }
    
    public void setBacterias(String bacterias) {
        this.bacterias = bacterias;
    }
    public String getLevaduras() {
        return this.levaduras;
    }
    
    public void setLevaduras(String levaduras) {
        this.levaduras = levaduras;
    }
    public String getSangreoculta() {
        return this.sangreoculta;
    }
    
    public void setSangreoculta(String sangreoculta) {
        this.sangreoculta = sangreoculta;
    }
    public String getTrofozoitos() {
        return this.trofozoitos;
    }
    
    public void setTrofozoitos(String trofozoitos) {
        this.trofozoitos = trofozoitos;
    }
    public String getHuevos() {
        return this.huevos;
    }
    
    public void setHuevos(String huevos) {
        this.huevos = huevos;
    }
    public String getQuistes() {
        return this.quistes;
    }
    
    public void setQuistes(String quistes) {
        this.quistes = quistes;
    }
    public String getLarvas() {
        return this.larvas;
    }
    
    public void setLarvas(String larvas) {
        this.larvas = larvas;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }




}


