package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0



/**
 * HematologiaExamena generated by hbm2java
 */
public class HematologiaExamena  implements java.io.Serializable {


     private int idhematologiaexamena;
     private Integer idhematologia;
     private String globrojo;
     private String hematrocitos;
     private String hemoglobina;
     private String vcm;
     private String hcm;
     private String bhcm;
     private Hematologia hematologia;

    public HematologiaExamena() {
    }

	
    public HematologiaExamena(int idhematologiaexamena) {
        this.idhematologiaexamena = idhematologiaexamena;
    }
    public HematologiaExamena(int idhematologiaexamena, Integer idhematologia, String globrojo, String hematrocitos, String hemoglobina, String vcm, String hcm, String bhcm, Hematologia hematologia) {
       this.idhematologiaexamena = idhematologiaexamena;
       this.idhematologia = idhematologia;
       this.globrojo = globrojo;
       this.hematrocitos = hematrocitos;
       this.hemoglobina = hemoglobina;
       this.vcm = vcm;
       this.hcm = hcm;
       this.bhcm = bhcm;
       this.hematologia = hematologia;
    }
   
    public int getIdhematologiaexamena() {
        return this.idhematologiaexamena;
    }
    
    public void setIdhematologiaexamena(int idhematologiaexamena) {
        this.idhematologiaexamena = idhematologiaexamena;
    }
    public Integer getIdhematologia() {
        return this.idhematologia;
    }
    
    public void setIdhematologia(Integer idhematologia) {
        this.idhematologia = idhematologia;
    }
    public String getGlobrojo() {
        return this.globrojo;
    }
    
    public void setGlobrojo(String globrojo) {
        this.globrojo = globrojo;
    }
    public String getHematrocitos() {
        return this.hematrocitos;
    }
    
    public void setHematrocitos(String hematrocitos) {
        this.hematrocitos = hematrocitos;
    }
    public String getHemoglobina() {
        return this.hemoglobina;
    }
    
    public void setHemoglobina(String hemoglobina) {
        this.hemoglobina = hemoglobina;
    }
    public String getVcm() {
        return this.vcm;
    }
    
    public void setVcm(String vcm) {
        this.vcm = vcm;
    }
    public String getHcm() {
        return this.hcm;
    }
    
    public void setHcm(String hcm) {
        this.hcm = hcm;
    }
    public String getBhcm() {
        return this.bhcm;
    }
    
    public void setBhcm(String bhcm) {
        this.bhcm = bhcm;
    }
    public Hematologia getHematologia() {
        return this.hematologia;
    }
    
    public void setHematologia(Hematologia hematologia) {
        this.hematologia = hematologia;
    }




}


