package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0



/**
 * HematologiaExamenb generated by hbm2java
 */
public class HematologiaExamenb  implements java.io.Serializable {


     private int idhematologiaexamenb;
     private Integer idhematologia;
     private String globblancos;
     private String neutrofiliossegmen;
     private String neutrofiliosbanda;
     private String linfocitos;
     private String eosinofilos;
     private String monocitos;
     private String basofilos;
     private Hematologia hematologia;

    public HematologiaExamenb() {
    }

	
    public HematologiaExamenb(int idhematologiaexamenb) {
        this.idhematologiaexamenb = idhematologiaexamenb;
    }
    public HematologiaExamenb(int idhematologiaexamenb, Integer idhematologia, String globblancos, String neutrofiliossegmen, String neutrofiliosbanda, String linfocitos, String eosinofilos, String monocitos, String basofilos, Hematologia hematologia) {
       this.idhematologiaexamenb = idhematologiaexamenb;
       this.idhematologia = idhematologia;
       this.globblancos = globblancos;
       this.neutrofiliossegmen = neutrofiliossegmen;
       this.neutrofiliosbanda = neutrofiliosbanda;
       this.linfocitos = linfocitos;
       this.eosinofilos = eosinofilos;
       this.monocitos = monocitos;
       this.basofilos = basofilos;
       this.hematologia = hematologia;
    }
   
    public int getIdhematologiaexamenb() {
        return this.idhematologiaexamenb;
    }
    
    public void setIdhematologiaexamenb(int idhematologiaexamenb) {
        this.idhematologiaexamenb = idhematologiaexamenb;
    }
    public Integer getIdhematologia() {
        return this.idhematologia;
    }
    
    public void setIdhematologia(Integer idhematologia) {
        this.idhematologia = idhematologia;
    }
    public String getGlobblancos() {
        return this.globblancos;
    }
    
    public void setGlobblancos(String globblancos) {
        this.globblancos = globblancos;
    }
    public String getNeutrofiliossegmen() {
        return this.neutrofiliossegmen;
    }
    
    public void setNeutrofiliossegmen(String neutrofiliossegmen) {
        this.neutrofiliossegmen = neutrofiliossegmen;
    }
    public String getNeutrofiliosbanda() {
        return this.neutrofiliosbanda;
    }
    
    public void setNeutrofiliosbanda(String neutrofiliosbanda) {
        this.neutrofiliosbanda = neutrofiliosbanda;
    }
    public String getLinfocitos() {
        return this.linfocitos;
    }
    
    public void setLinfocitos(String linfocitos) {
        this.linfocitos = linfocitos;
    }
    public String getEosinofilos() {
        return this.eosinofilos;
    }
    
    public void setEosinofilos(String eosinofilos) {
        this.eosinofilos = eosinofilos;
    }
    public String getMonocitos() {
        return this.monocitos;
    }
    
    public void setMonocitos(String monocitos) {
        this.monocitos = monocitos;
    }
    public String getBasofilos() {
        return this.basofilos;
    }
    
    public void setBasofilos(String basofilos) {
        this.basofilos = basofilos;
    }
    public Hematologia getHematologia() {
        return this.hematologia;
    }
    
    public void setHematologia(Hematologia hematologia) {
        this.hematologia = hematologia;
    }




}


