package entities;
// Generated 07-sep-2015 20:24:23 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hematologia generated by hbm2java
 */
public class Hematologia  implements java.io.Serializable {


     private Integer idhematologia;
     private Pacientes pacientes;
     private Doctores doctores;
     private Date fecha;
     private String celulasle;
     private String gotagruesa;
     private String plaquetas;
     private String reticulocitos;
     private String eritrosedimentacion;
     private String fsangreperiferica;
     private String observaciones;
     private Set<HematologiaExamenb> hematologiaExamenbs = new HashSet<HematologiaExamenb>(0);
     private Set<HematologiaExamena> hematologiaExamenas = new HashSet<HematologiaExamena>(0);

    public Hematologia() {
    }

    public Hematologia(Pacientes pacientes, Doctores doctores, Date fecha, String celulasle, String gotagruesa, String plaquetas, String reticulocitos, String eritrosedimentacion, String fsangreperiferica, String observaciones, Set<HematologiaExamenb> hematologiaExamenbs, Set<HematologiaExamena> hematologiaExamenas) {
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.fecha = fecha;
       this.celulasle = celulasle;
       this.gotagruesa = gotagruesa;
       this.plaquetas = plaquetas;
       this.reticulocitos = reticulocitos;
       this.eritrosedimentacion = eritrosedimentacion;
       this.fsangreperiferica = fsangreperiferica;
       this.observaciones = observaciones;
       this.hematologiaExamenbs = hematologiaExamenbs;
       this.hematologiaExamenas = hematologiaExamenas;
    }
   
    public Integer getIdhematologia() {
        return this.idhematologia;
    }
    
    public void setIdhematologia(Integer idhematologia) {
        this.idhematologia = idhematologia;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCelulasle() {
        return this.celulasle;
    }
    
    public void setCelulasle(String celulasle) {
        this.celulasle = celulasle;
    }
    public String getGotagruesa() {
        return this.gotagruesa;
    }
    
    public void setGotagruesa(String gotagruesa) {
        this.gotagruesa = gotagruesa;
    }
    public String getPlaquetas() {
        return this.plaquetas;
    }
    
    public void setPlaquetas(String plaquetas) {
        this.plaquetas = plaquetas;
    }
    public String getReticulocitos() {
        return this.reticulocitos;
    }
    
    public void setReticulocitos(String reticulocitos) {
        this.reticulocitos = reticulocitos;
    }
    public String getEritrosedimentacion() {
        return this.eritrosedimentacion;
    }
    
    public void setEritrosedimentacion(String eritrosedimentacion) {
        this.eritrosedimentacion = eritrosedimentacion;
    }
    public String getFsangreperiferica() {
        return this.fsangreperiferica;
    }
    
    public void setFsangreperiferica(String fsangreperiferica) {
        this.fsangreperiferica = fsangreperiferica;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<HematologiaExamenb> getHematologiaExamenbs() {
        return this.hematologiaExamenbs;
    }
    
    public void setHematologiaExamenbs(Set<HematologiaExamenb> hematologiaExamenbs) {
        this.hematologiaExamenbs = hematologiaExamenbs;
    }
    public Set<HematologiaExamena> getHematologiaExamenas() {
        return this.hematologiaExamenas;
    }
    
    public void setHematologiaExamenas(Set<HematologiaExamena> hematologiaExamenas) {
        this.hematologiaExamenas = hematologiaExamenas;
    }




}


