package entities;
// Generated 07-sep-2015 11:55:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Inmunologia generated by hbm2java
 */
public class Inmunologia  implements java.io.Serializable {


     private Integer idinmunidad;
     private Pacientes pacientes;
     private Doctores doctores;
     private Date fecha;
     private String tificoo;
     private String tificoh;
     private String paratificoa;
     private String paratificob;
     private String proteux19;
     private String brucella;
     private String vdrl;
     private String latexra;
     private String proteinac;
     private String monotest;
     private String antiestreptolisinao;
     private String embarazoorina;
     private String embarazosangre;
     private String vih;
     private String hbs;

    public Inmunologia() {
    }

    public Inmunologia(Pacientes pacientes, Doctores doctores, Date fecha, String tificoo, String tificoh, String paratificoa, String paratificob, String proteux19, String brucella, String vdrl, String latexra, String proteinac, String monotest, String antiestreptolisinao, String embarazoorina, String embarazosangre, String vih, String hbs) {
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.fecha = fecha;
       this.tificoo = tificoo;
       this.tificoh = tificoh;
       this.paratificoa = paratificoa;
       this.paratificob = paratificob;
       this.proteux19 = proteux19;
       this.brucella = brucella;
       this.vdrl = vdrl;
       this.latexra = latexra;
       this.proteinac = proteinac;
       this.monotest = monotest;
       this.antiestreptolisinao = antiestreptolisinao;
       this.embarazoorina = embarazoorina;
       this.embarazosangre = embarazosangre;
       this.vih = vih;
       this.hbs = hbs;
    }
   
    public Integer getIdinmunidad() {
        return this.idinmunidad;
    }
    
    public void setIdinmunidad(Integer idinmunidad) {
        this.idinmunidad = idinmunidad;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTificoo() {
        return this.tificoo;
    }
    
    public void setTificoo(String tificoo) {
        this.tificoo = tificoo;
    }
    public String getTificoh() {
        return this.tificoh;
    }
    
    public void setTificoh(String tificoh) {
        this.tificoh = tificoh;
    }
    public String getParatificoa() {
        return this.paratificoa;
    }
    
    public void setParatificoa(String paratificoa) {
        this.paratificoa = paratificoa;
    }
    public String getParatificob() {
        return this.paratificob;
    }
    
    public void setParatificob(String paratificob) {
        this.paratificob = paratificob;
    }
    public String getProteux19() {
        return this.proteux19;
    }
    
    public void setProteux19(String proteux19) {
        this.proteux19 = proteux19;
    }
    public String getBrucella() {
        return this.brucella;
    }
    
    public void setBrucella(String brucella) {
        this.brucella = brucella;
    }
    public String getVdrl() {
        return this.vdrl;
    }
    
    public void setVdrl(String vdrl) {
        this.vdrl = vdrl;
    }
    public String getLatexra() {
        return this.latexra;
    }
    
    public void setLatexra(String latexra) {
        this.latexra = latexra;
    }
    public String getProteinac() {
        return this.proteinac;
    }
    
    public void setProteinac(String proteinac) {
        this.proteinac = proteinac;
    }
    public String getMonotest() {
        return this.monotest;
    }
    
    public void setMonotest(String monotest) {
        this.monotest = monotest;
    }
    public String getAntiestreptolisinao() {
        return this.antiestreptolisinao;
    }
    
    public void setAntiestreptolisinao(String antiestreptolisinao) {
        this.antiestreptolisinao = antiestreptolisinao;
    }
    public String getEmbarazoorina() {
        return this.embarazoorina;
    }
    
    public void setEmbarazoorina(String embarazoorina) {
        this.embarazoorina = embarazoorina;
    }
    public String getEmbarazosangre() {
        return this.embarazosangre;
    }
    
    public void setEmbarazosangre(String embarazosangre) {
        this.embarazosangre = embarazosangre;
    }
    public String getVih() {
        return this.vih;
    }
    
    public void setVih(String vih) {
        this.vih = vih;
    }
    public String getHbs() {
        return this.hbs;
    }
    
    public void setHbs(String hbs) {
        this.hbs = hbs;
    }




}


