package entities;
// Generated 07-sep-2015 20:24:23 by Hibernate Tools 3.6.0



/**
 * OrinaMicroscopico generated by hbm2java
 */
public class OrinaMicroscopico  implements java.io.Serializable {


     private Integer idmicroscopico;
     private Orina orina;
     private String leucocitarios;
     private String hematicos;
     private String granulosos;
     private String cereos;
     private String epiteliales;
     private String hialinos;
     private String leucocitos;
     private String hematies;
     private String celepiteliales;
     private String bacterias;
     private String mucoides;
     private String cristales;

    public OrinaMicroscopico() {
    }

    public OrinaMicroscopico(Orina orina, String leucocitarios, String hematicos, String granulosos, String cereos, String epiteliales, String hialinos, String leucocitos, String hematies, String celepiteliales, String bacterias, String mucoides, String cristales) {
       this.orina = orina;
       this.leucocitarios = leucocitarios;
       this.hematicos = hematicos;
       this.granulosos = granulosos;
       this.cereos = cereos;
       this.epiteliales = epiteliales;
       this.hialinos = hialinos;
       this.leucocitos = leucocitos;
       this.hematies = hematies;
       this.celepiteliales = celepiteliales;
       this.bacterias = bacterias;
       this.mucoides = mucoides;
       this.cristales = cristales;
    }
   
    public Integer getIdmicroscopico() {
        return this.idmicroscopico;
    }
    
    public void setIdmicroscopico(Integer idmicroscopico) {
        this.idmicroscopico = idmicroscopico;
    }
    public Orina getOrina() {
        return this.orina;
    }
    
    public void setOrina(Orina orina) {
        this.orina = orina;
    }
    public String getLeucocitarios() {
        return this.leucocitarios;
    }
    
    public void setLeucocitarios(String leucocitarios) {
        this.leucocitarios = leucocitarios;
    }
    public String getHematicos() {
        return this.hematicos;
    }
    
    public void setHematicos(String hematicos) {
        this.hematicos = hematicos;
    }
    public String getGranulosos() {
        return this.granulosos;
    }
    
    public void setGranulosos(String granulosos) {
        this.granulosos = granulosos;
    }
    public String getCereos() {
        return this.cereos;
    }
    
    public void setCereos(String cereos) {
        this.cereos = cereos;
    }
    public String getEpiteliales() {
        return this.epiteliales;
    }
    
    public void setEpiteliales(String epiteliales) {
        this.epiteliales = epiteliales;
    }
    public String getHialinos() {
        return this.hialinos;
    }
    
    public void setHialinos(String hialinos) {
        this.hialinos = hialinos;
    }
    public String getLeucocitos() {
        return this.leucocitos;
    }
    
    public void setLeucocitos(String leucocitos) {
        this.leucocitos = leucocitos;
    }
    public String getHematies() {
        return this.hematies;
    }
    
    public void setHematies(String hematies) {
        this.hematies = hematies;
    }
    public String getCelepiteliales() {
        return this.celepiteliales;
    }
    
    public void setCelepiteliales(String celepiteliales) {
        this.celepiteliales = celepiteliales;
    }
    public String getBacterias() {
        return this.bacterias;
    }
    
    public void setBacterias(String bacterias) {
        this.bacterias = bacterias;
    }
    public String getMucoides() {
        return this.mucoides;
    }
    
    public void setMucoides(String mucoides) {
        this.mucoides = mucoides;
    }
    public String getCristales() {
        return this.cristales;
    }
    
    public void setCristales(String cristales) {
        this.cristales = cristales;
    }




}


