package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Orina generated by hbm2java
 */
public class Orina  implements java.io.Serializable {


     private int idorina;
     private OrinaMicroscopico orinaMicroscopico;
     private Pacientes pacientes;
     private Doctores doctores;
     private Date fecha;
     private String observaciones;

    public Orina() {
    }

	
    public Orina(OrinaMicroscopico orinaMicroscopico) {
        this.orinaMicroscopico = orinaMicroscopico;
    }
    public Orina(OrinaMicroscopico orinaMicroscopico, Pacientes pacientes, Doctores doctores, Date fecha, String observaciones) {
       this.orinaMicroscopico = orinaMicroscopico;
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.fecha = fecha;
       this.observaciones = observaciones;
    }
   
    public int getIdorina() {
        return this.idorina;
    }
    
    public void setIdorina(int idorina) {
        this.idorina = idorina;
    }
    public OrinaMicroscopico getOrinaMicroscopico() {
        return this.orinaMicroscopico;
    }
    
    public void setOrinaMicroscopico(OrinaMicroscopico orinaMicroscopico) {
        this.orinaMicroscopico = orinaMicroscopico;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


