package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0



/**
 * OrinaFisicoQuimico generated by hbm2java
 */
public class OrinaFisicoQuimico  implements java.io.Serializable {


     private int idfisicoquimico;
     private Integer idorina;
     private String color;
     private String aspecto;
     private String densidad;
     private String ph;
     private String nitritos;
     private String proteinas;
     private String glucos;
     private String bilirrubina;
     private String cetonas;
     private String sangre;
     private String urobilinogeno;

    public OrinaFisicoQuimico() {
    }

	
    public OrinaFisicoQuimico(int idfisicoquimico) {
        this.idfisicoquimico = idfisicoquimico;
    }
    public OrinaFisicoQuimico(int idfisicoquimico, Integer idorina, String color, String aspecto, String densidad, String ph, String nitritos, String proteinas, String glucos, String bilirrubina, String cetonas, String sangre, String urobilinogeno) {
       this.idfisicoquimico = idfisicoquimico;
       this.idorina = idorina;
       this.color = color;
       this.aspecto = aspecto;
       this.densidad = densidad;
       this.ph = ph;
       this.nitritos = nitritos;
       this.proteinas = proteinas;
       this.glucos = glucos;
       this.bilirrubina = bilirrubina;
       this.cetonas = cetonas;
       this.sangre = sangre;
       this.urobilinogeno = urobilinogeno;
    }
   
    public int getIdfisicoquimico() {
        return this.idfisicoquimico;
    }
    
    public void setIdfisicoquimico(int idfisicoquimico) {
        this.idfisicoquimico = idfisicoquimico;
    }
    public Integer getIdorina() {
        return this.idorina;
    }
    
    public void setIdorina(Integer idorina) {
        this.idorina = idorina;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getAspecto() {
        return this.aspecto;
    }
    
    public void setAspecto(String aspecto) {
        this.aspecto = aspecto;
    }
    public String getDensidad() {
        return this.densidad;
    }
    
    public void setDensidad(String densidad) {
        this.densidad = densidad;
    }
    public String getPh() {
        return this.ph;
    }
    
    public void setPh(String ph) {
        this.ph = ph;
    }
    public String getNitritos() {
        return this.nitritos;
    }
    
    public void setNitritos(String nitritos) {
        this.nitritos = nitritos;
    }
    public String getProteinas() {
        return this.proteinas;
    }
    
    public void setProteinas(String proteinas) {
        this.proteinas = proteinas;
    }
    public String getGlucos() {
        return this.glucos;
    }
    
    public void setGlucos(String glucos) {
        this.glucos = glucos;
    }
    public String getBilirrubina() {
        return this.bilirrubina;
    }
    
    public void setBilirrubina(String bilirrubina) {
        this.bilirrubina = bilirrubina;
    }
    public String getCetonas() {
        return this.cetonas;
    }
    
    public void setCetonas(String cetonas) {
        this.cetonas = cetonas;
    }
    public String getSangre() {
        return this.sangre;
    }
    
    public void setSangre(String sangre) {
        this.sangre = sangre;
    }
    public String getUrobilinogeno() {
        return this.urobilinogeno;
    }
    
    public void setUrobilinogeno(String urobilinogeno) {
        this.urobilinogeno = urobilinogeno;
    }




}


