package entities;
// Generated 07-sep-2015 11:55:40 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer idpaciente;
     private String nombre;
     private String edad;
     private Set<Bacteriologia> bacteriologias = new HashSet<Bacteriologia>(0);
     private Set<Quimica> quimicas = new HashSet<Quimica>(0);
     private Set<Heces> heceses = new HashSet<Heces>(0);
     private Set<Orina> orinas = new HashSet<Orina>(0);
     private Set<Hematologia> hematologias = new HashSet<Hematologia>(0);
     private Set<Inmunologia> inmunologias = new HashSet<Inmunologia>(0);

    public Pacientes() {
    }

    public Pacientes(String nombre, String edad, Set<Bacteriologia> bacteriologias, Set<Quimica> quimicas, Set<Heces> heceses, Set<Orina> orinas, Set<Hematologia> hematologias, Set<Inmunologia> inmunologias) {
       this.nombre = nombre;
       this.edad = edad;
       this.bacteriologias = bacteriologias;
       this.quimicas = quimicas;
       this.heceses = heceses;
       this.orinas = orinas;
       this.hematologias = hematologias;
       this.inmunologias = inmunologias;
    }
   
    public Integer getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(Integer idpaciente) {
        this.idpaciente = idpaciente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public Set<Bacteriologia> getBacteriologias() {
        return this.bacteriologias;
    }
    
    public void setBacteriologias(Set<Bacteriologia> bacteriologias) {
        this.bacteriologias = bacteriologias;
    }
    public Set<Quimica> getQuimicas() {
        return this.quimicas;
    }
    
    public void setQuimicas(Set<Quimica> quimicas) {
        this.quimicas = quimicas;
    }
    public Set<Heces> getHeceses() {
        return this.heceses;
    }
    
    public void setHeceses(Set<Heces> heceses) {
        this.heceses = heceses;
    }
    public Set<Orina> getOrinas() {
        return this.orinas;
    }
    
    public void setOrinas(Set<Orina> orinas) {
        this.orinas = orinas;
    }
    public Set<Hematologia> getHematologias() {
        return this.hematologias;
    }
    
    public void setHematologias(Set<Hematologia> hematologias) {
        this.hematologias = hematologias;
    }
    public Set<Inmunologia> getInmunologias() {
        return this.inmunologias;
    }
    
    public void setInmunologias(Set<Inmunologia> inmunologias) {
        this.inmunologias = inmunologias;
    }




}


