package entities;
// Generated 01-sep-2015 14:16:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Quimica generated by hbm2java
 */
public class Quimica  implements java.io.Serializable {


     private int idquimica;
     private Pacientes pacientes;
     private Doctores doctores;
     private Date fecha;

    public Quimica() {
    }

	
    public Quimica(int idquimica) {
        this.idquimica = idquimica;
    }
    public Quimica(int idquimica, Pacientes pacientes, Doctores doctores, Date fecha) {
       this.idquimica = idquimica;
       this.pacientes = pacientes;
       this.doctores = doctores;
       this.fecha = fecha;
    }
   
    public int getIdquimica() {
        return this.idquimica;
    }
    
    public void setIdquimica(int idquimica) {
        this.idquimica = idquimica;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Doctores getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(Doctores doctores) {
        this.doctores = doctores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


